spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.paypalservice.entity.Order"
        "[spring.json.trusted.packages]": "edu.miu.paypalservice"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: "localhost:9092"
kafka:
  topic: "PaymentOrderEvent"

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
kafka:
  topic: ${PAYMENT_ORDER_EVENT}
---
server:
  port: 8081
