spring:
  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.creditservice.entity.Credit"
        "[spring.json.trusted.packages]": "edu.miu.creditservice"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: "localhost:9092"

  main:
    allow-bean-definition-overriding: true

  data:
    cassandra:
      contact-points: "localhost:9042"
      keyspace-name: credit_ks
      #port: 9042
      schema-action: create_if_not_exists
      local-datacenter: datacenter1

kafka:
  topicCredit: "CREDIT_TOPIC"
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
kafka:
  topicCredit: ${CREDIT_TOPIC}
---
server:
  port: 8083
